name: Docker

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  compose-build:
    name: Compose Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build
